name: simplefaas
dependencies:
    start:
    uuid:
    jaguar_query:
    jaguar_orm:
    postgresql2:
    stream:
    logging: '>=0.11.3 <0.12.0'
    http: ^0.12.2
    hive: ^1.4.4+1
    yaml: ^2.2.1

dev_dependencies:
  build_runner:
  jaguar_orm_gen:
  test: ^1.0.0

