name: simplefaas
dependencies:
  uuid:
  jaguar_query:
  jaguar_orm:
  postgresql2:
  stream:
  logging:
  http:
  hive:
  yaml: 3.1.0
  jaguar:
  jaguar_cors:
  crypto:

dev_dependencies:
  build_runner:
  test: ^1.0.0

environment:
  sdk: '>=2.11.0 <3.0.0'
