name: simplefaas
dependencies:
  uuid:
  postgresql2:
  stream:
  logging:
  http:
  hive:
  yaml: 3.1.0
  crypto:
  alfred:
    git:
      url: https://github.com/rknell/alfred

dev_dependencies:
  build_runner:
  test: ^1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
